// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v0.14.1-v0.14.0-bufbuild-protocompile-easyp
// source: api/proto/gateway.proto

package gatewaypb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	GatewayAPI_DeployProcess_FullMethodName                   = "/rumunda.gateway.v1.GatewayAPI/DeployProcess"
	GatewayAPI_CreateProcessInstance_FullMethodName           = "/rumunda.gateway.v1.GatewayAPI/CreateProcessInstance"
	GatewayAPI_CreateProcessInstanceWithResult_FullMethodName = "/rumunda.gateway.v1.GatewayAPI/CreateProcessInstanceWithResult"
	GatewayAPI_ActivateJobs_FullMethodName                    = "/rumunda.gateway.v1.GatewayAPI/ActivateJobs"
	GatewayAPI_StreamActivatedJobs_FullMethodName             = "/rumunda.gateway.v1.GatewayAPI/StreamActivatedJobs"
	GatewayAPI_CompleteJob_FullMethodName                     = "/rumunda.gateway.v1.GatewayAPI/CompleteJob"
	GatewayAPI_BroadcastSignal_FullMethodName                 = "/rumunda.gateway.v1.GatewayAPI/BroadcastSignal"
	GatewayAPI_PublishMessage_FullMethodName                  = "/rumunda.gateway.v1.GatewayAPI/PublishMessage"
	GatewayAPI_UpdateJobRetries_FullMethodName                = "/rumunda.gateway.v1.GatewayAPI/UpdateJobRetries"
	GatewayAPI_UpdateJobTimeout_FullMethodName                = "/rumunda.gateway.v1.GatewayAPI/UpdateJobTimeout"
	GatewayAPI_DeleteResource_FullMethodName                  = "/rumunda.gateway.v1.GatewayAPI/DeleteResource"
	GatewayAPI_ActivateElement_FullMethodName                 = "/rumunda.gateway.v1.GatewayAPI/ActivateElement"
)

// GatewayAPIClient is the client API for GatewayAPI service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// GatewayAPI is the external command API for the BPMN engine.
type GatewayAPIClient interface {
	// DeployProcess deploys a BPMN process definition.
	DeployProcess(ctx context.Context, in *DeployProcessRequest, opts ...grpc.CallOption) (*DeployProcessResponse, error)
	// CreateProcessInstance starts a new process instance.
	CreateProcessInstance(ctx context.Context, in *CreateProcessInstanceRequest, opts ...grpc.CallOption) (*CreateProcessInstanceResponse, error)
	// CreateProcessInstanceWithResult starts a process and waits for it to complete.
	CreateProcessInstanceWithResult(ctx context.Context, in *CreateProcessInstanceWithResultRequest, opts ...grpc.CallOption) (*CreateProcessInstanceWithResultResponse, error)
	// ActivateJobs returns available jobs for a given type (long-poll).
	ActivateJobs(ctx context.Context, in *ActivateJobsRequest, opts ...grpc.CallOption) (*ActivateJobsResponse, error)
	// StreamActivatedJobs opens a server-side stream that pushes jobs to the worker
	// as they become available. The worker receives jobs one by one and processes them.
	StreamActivatedJobs(ctx context.Context, in *StreamActivatedJobsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ActivatedJob], error)
	// CompleteJob marks a job as completed.
	CompleteJob(ctx context.Context, in *CompleteJobRequest, opts ...grpc.CallOption) (*CompleteJobResponse, error)
	// BroadcastSignal broadcasts a BPMN signal.
	BroadcastSignal(ctx context.Context, in *BroadcastSignalRequest, opts ...grpc.CallOption) (*BroadcastSignalResponse, error)
	// PublishMessage publishes a message for correlation.
	PublishMessage(ctx context.Context, in *PublishMessageRequest, opts ...grpc.CallOption) (*PublishMessageResponse, error)
	// UpdateJobRetries updates the retry count of a job.
	UpdateJobRetries(ctx context.Context, in *UpdateJobRetriesRequest, opts ...grpc.CallOption) (*UpdateJobRetriesResponse, error)
	// UpdateJobTimeout updates the deadline of an activated job.
	UpdateJobTimeout(ctx context.Context, in *UpdateJobTimeoutRequest, opts ...grpc.CallOption) (*UpdateJobTimeoutResponse, error)
	// DeleteResource soft-deletes a deployed resource (process definition or form).
	DeleteResource(ctx context.Context, in *DeleteResourceRequest, opts ...grpc.CallOption) (*DeleteResourceResponse, error)
	// ActivateElement activates an element inside an ad-hoc subprocess.
	ActivateElement(ctx context.Context, in *ActivateElementRequest, opts ...grpc.CallOption) (*ActivateElementResponse, error)
}

type gatewayAPIClient struct {
	cc grpc.ClientConnInterface
}

func NewGatewayAPIClient(cc grpc.ClientConnInterface) GatewayAPIClient {
	return &gatewayAPIClient{cc}
}

func (c *gatewayAPIClient) DeployProcess(ctx context.Context, in *DeployProcessRequest, opts ...grpc.CallOption) (*DeployProcessResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeployProcessResponse)
	err := c.cc.Invoke(ctx, GatewayAPI_DeployProcess_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gatewayAPIClient) CreateProcessInstance(ctx context.Context, in *CreateProcessInstanceRequest, opts ...grpc.CallOption) (*CreateProcessInstanceResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateProcessInstanceResponse)
	err := c.cc.Invoke(ctx, GatewayAPI_CreateProcessInstance_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gatewayAPIClient) CreateProcessInstanceWithResult(ctx context.Context, in *CreateProcessInstanceWithResultRequest, opts ...grpc.CallOption) (*CreateProcessInstanceWithResultResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateProcessInstanceWithResultResponse)
	err := c.cc.Invoke(ctx, GatewayAPI_CreateProcessInstanceWithResult_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gatewayAPIClient) ActivateJobs(ctx context.Context, in *ActivateJobsRequest, opts ...grpc.CallOption) (*ActivateJobsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ActivateJobsResponse)
	err := c.cc.Invoke(ctx, GatewayAPI_ActivateJobs_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gatewayAPIClient) StreamActivatedJobs(ctx context.Context, in *StreamActivatedJobsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ActivatedJob], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &GatewayAPI_ServiceDesc.Streams[0], GatewayAPI_StreamActivatedJobs_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[StreamActivatedJobsRequest, ActivatedJob]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type GatewayAPI_StreamActivatedJobsClient = grpc.ServerStreamingClient[ActivatedJob]

func (c *gatewayAPIClient) CompleteJob(ctx context.Context, in *CompleteJobRequest, opts ...grpc.CallOption) (*CompleteJobResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CompleteJobResponse)
	err := c.cc.Invoke(ctx, GatewayAPI_CompleteJob_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gatewayAPIClient) BroadcastSignal(ctx context.Context, in *BroadcastSignalRequest, opts ...grpc.CallOption) (*BroadcastSignalResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BroadcastSignalResponse)
	err := c.cc.Invoke(ctx, GatewayAPI_BroadcastSignal_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gatewayAPIClient) PublishMessage(ctx context.Context, in *PublishMessageRequest, opts ...grpc.CallOption) (*PublishMessageResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PublishMessageResponse)
	err := c.cc.Invoke(ctx, GatewayAPI_PublishMessage_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gatewayAPIClient) UpdateJobRetries(ctx context.Context, in *UpdateJobRetriesRequest, opts ...grpc.CallOption) (*UpdateJobRetriesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateJobRetriesResponse)
	err := c.cc.Invoke(ctx, GatewayAPI_UpdateJobRetries_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gatewayAPIClient) UpdateJobTimeout(ctx context.Context, in *UpdateJobTimeoutRequest, opts ...grpc.CallOption) (*UpdateJobTimeoutResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateJobTimeoutResponse)
	err := c.cc.Invoke(ctx, GatewayAPI_UpdateJobTimeout_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gatewayAPIClient) DeleteResource(ctx context.Context, in *DeleteResourceRequest, opts ...grpc.CallOption) (*DeleteResourceResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteResourceResponse)
	err := c.cc.Invoke(ctx, GatewayAPI_DeleteResource_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gatewayAPIClient) ActivateElement(ctx context.Context, in *ActivateElementRequest, opts ...grpc.CallOption) (*ActivateElementResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ActivateElementResponse)
	err := c.cc.Invoke(ctx, GatewayAPI_ActivateElement_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GatewayAPIServer is the server API for GatewayAPI service.
// All implementations must embed UnimplementedGatewayAPIServer
// for forward compatibility.
//
// GatewayAPI is the external command API for the BPMN engine.
type GatewayAPIServer interface {
	// DeployProcess deploys a BPMN process definition.
	DeployProcess(context.Context, *DeployProcessRequest) (*DeployProcessResponse, error)
	// CreateProcessInstance starts a new process instance.
	CreateProcessInstance(context.Context, *CreateProcessInstanceRequest) (*CreateProcessInstanceResponse, error)
	// CreateProcessInstanceWithResult starts a process and waits for it to complete.
	CreateProcessInstanceWithResult(context.Context, *CreateProcessInstanceWithResultRequest) (*CreateProcessInstanceWithResultResponse, error)
	// ActivateJobs returns available jobs for a given type (long-poll).
	ActivateJobs(context.Context, *ActivateJobsRequest) (*ActivateJobsResponse, error)
	// StreamActivatedJobs opens a server-side stream that pushes jobs to the worker
	// as they become available. The worker receives jobs one by one and processes them.
	StreamActivatedJobs(*StreamActivatedJobsRequest, grpc.ServerStreamingServer[ActivatedJob]) error
	// CompleteJob marks a job as completed.
	CompleteJob(context.Context, *CompleteJobRequest) (*CompleteJobResponse, error)
	// BroadcastSignal broadcasts a BPMN signal.
	BroadcastSignal(context.Context, *BroadcastSignalRequest) (*BroadcastSignalResponse, error)
	// PublishMessage publishes a message for correlation.
	PublishMessage(context.Context, *PublishMessageRequest) (*PublishMessageResponse, error)
	// UpdateJobRetries updates the retry count of a job.
	UpdateJobRetries(context.Context, *UpdateJobRetriesRequest) (*UpdateJobRetriesResponse, error)
	// UpdateJobTimeout updates the deadline of an activated job.
	UpdateJobTimeout(context.Context, *UpdateJobTimeoutRequest) (*UpdateJobTimeoutResponse, error)
	// DeleteResource soft-deletes a deployed resource (process definition or form).
	DeleteResource(context.Context, *DeleteResourceRequest) (*DeleteResourceResponse, error)
	// ActivateElement activates an element inside an ad-hoc subprocess.
	ActivateElement(context.Context, *ActivateElementRequest) (*ActivateElementResponse, error)
	mustEmbedUnimplementedGatewayAPIServer()
}

// UnimplementedGatewayAPIServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedGatewayAPIServer struct{}

func (UnimplementedGatewayAPIServer) DeployProcess(context.Context, *DeployProcessRequest) (*DeployProcessResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeployProcess not implemented")
}
func (UnimplementedGatewayAPIServer) CreateProcessInstance(context.Context, *CreateProcessInstanceRequest) (*CreateProcessInstanceResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateProcessInstance not implemented")
}
func (UnimplementedGatewayAPIServer) CreateProcessInstanceWithResult(context.Context, *CreateProcessInstanceWithResultRequest) (*CreateProcessInstanceWithResultResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateProcessInstanceWithResult not implemented")
}
func (UnimplementedGatewayAPIServer) ActivateJobs(context.Context, *ActivateJobsRequest) (*ActivateJobsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ActivateJobs not implemented")
}
func (UnimplementedGatewayAPIServer) StreamActivatedJobs(*StreamActivatedJobsRequest, grpc.ServerStreamingServer[ActivatedJob]) error {
	return status.Errorf(codes.Unimplemented, "method StreamActivatedJobs not implemented")
}
func (UnimplementedGatewayAPIServer) CompleteJob(context.Context, *CompleteJobRequest) (*CompleteJobResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CompleteJob not implemented")
}
func (UnimplementedGatewayAPIServer) BroadcastSignal(context.Context, *BroadcastSignalRequest) (*BroadcastSignalResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method BroadcastSignal not implemented")
}
func (UnimplementedGatewayAPIServer) PublishMessage(context.Context, *PublishMessageRequest) (*PublishMessageResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PublishMessage not implemented")
}
func (UnimplementedGatewayAPIServer) UpdateJobRetries(context.Context, *UpdateJobRetriesRequest) (*UpdateJobRetriesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateJobRetries not implemented")
}
func (UnimplementedGatewayAPIServer) UpdateJobTimeout(context.Context, *UpdateJobTimeoutRequest) (*UpdateJobTimeoutResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateJobTimeout not implemented")
}
func (UnimplementedGatewayAPIServer) DeleteResource(context.Context, *DeleteResourceRequest) (*DeleteResourceResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteResource not implemented")
}
func (UnimplementedGatewayAPIServer) ActivateElement(context.Context, *ActivateElementRequest) (*ActivateElementResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ActivateElement not implemented")
}
func (UnimplementedGatewayAPIServer) mustEmbedUnimplementedGatewayAPIServer() {}
func (UnimplementedGatewayAPIServer) testEmbeddedByValue()                    {}

// UnsafeGatewayAPIServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to GatewayAPIServer will
// result in compilation errors.
type UnsafeGatewayAPIServer interface {
	mustEmbedUnimplementedGatewayAPIServer()
}

func RegisterGatewayAPIServer(s grpc.ServiceRegistrar, srv GatewayAPIServer) {
	// If the following call pancis, it indicates UnimplementedGatewayAPIServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&GatewayAPI_ServiceDesc, srv)
}

func _GatewayAPI_DeployProcess_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeployProcessRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GatewayAPIServer).DeployProcess(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GatewayAPI_DeployProcess_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GatewayAPIServer).DeployProcess(ctx, req.(*DeployProcessRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GatewayAPI_CreateProcessInstance_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateProcessInstanceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GatewayAPIServer).CreateProcessInstance(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GatewayAPI_CreateProcessInstance_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GatewayAPIServer).CreateProcessInstance(ctx, req.(*CreateProcessInstanceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GatewayAPI_CreateProcessInstanceWithResult_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateProcessInstanceWithResultRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GatewayAPIServer).CreateProcessInstanceWithResult(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GatewayAPI_CreateProcessInstanceWithResult_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GatewayAPIServer).CreateProcessInstanceWithResult(ctx, req.(*CreateProcessInstanceWithResultRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GatewayAPI_ActivateJobs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ActivateJobsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GatewayAPIServer).ActivateJobs(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GatewayAPI_ActivateJobs_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GatewayAPIServer).ActivateJobs(ctx, req.(*ActivateJobsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GatewayAPI_StreamActivatedJobs_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(StreamActivatedJobsRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(GatewayAPIServer).StreamActivatedJobs(m, &grpc.GenericServerStream[StreamActivatedJobsRequest, ActivatedJob]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type GatewayAPI_StreamActivatedJobsServer = grpc.ServerStreamingServer[ActivatedJob]

func _GatewayAPI_CompleteJob_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CompleteJobRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GatewayAPIServer).CompleteJob(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GatewayAPI_CompleteJob_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GatewayAPIServer).CompleteJob(ctx, req.(*CompleteJobRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GatewayAPI_BroadcastSignal_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BroadcastSignalRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GatewayAPIServer).BroadcastSignal(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GatewayAPI_BroadcastSignal_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GatewayAPIServer).BroadcastSignal(ctx, req.(*BroadcastSignalRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GatewayAPI_PublishMessage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PublishMessageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GatewayAPIServer).PublishMessage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GatewayAPI_PublishMessage_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GatewayAPIServer).PublishMessage(ctx, req.(*PublishMessageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GatewayAPI_UpdateJobRetries_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateJobRetriesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GatewayAPIServer).UpdateJobRetries(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GatewayAPI_UpdateJobRetries_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GatewayAPIServer).UpdateJobRetries(ctx, req.(*UpdateJobRetriesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GatewayAPI_UpdateJobTimeout_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateJobTimeoutRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GatewayAPIServer).UpdateJobTimeout(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GatewayAPI_UpdateJobTimeout_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GatewayAPIServer).UpdateJobTimeout(ctx, req.(*UpdateJobTimeoutRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GatewayAPI_DeleteResource_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteResourceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GatewayAPIServer).DeleteResource(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GatewayAPI_DeleteResource_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GatewayAPIServer).DeleteResource(ctx, req.(*DeleteResourceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GatewayAPI_ActivateElement_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ActivateElementRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GatewayAPIServer).ActivateElement(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GatewayAPI_ActivateElement_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GatewayAPIServer).ActivateElement(ctx, req.(*ActivateElementRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// GatewayAPI_ServiceDesc is the grpc.ServiceDesc for GatewayAPI service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var GatewayAPI_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "rumunda.gateway.v1.GatewayAPI",
	HandlerType: (*GatewayAPIServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "DeployProcess",
			Handler:    _GatewayAPI_DeployProcess_Handler,
		},
		{
			MethodName: "CreateProcessInstance",
			Handler:    _GatewayAPI_CreateProcessInstance_Handler,
		},
		{
			MethodName: "CreateProcessInstanceWithResult",
			Handler:    _GatewayAPI_CreateProcessInstanceWithResult_Handler,
		},
		{
			MethodName: "ActivateJobs",
			Handler:    _GatewayAPI_ActivateJobs_Handler,
		},
		{
			MethodName: "CompleteJob",
			Handler:    _GatewayAPI_CompleteJob_Handler,
		},
		{
			MethodName: "BroadcastSignal",
			Handler:    _GatewayAPI_BroadcastSignal_Handler,
		},
		{
			MethodName: "PublishMessage",
			Handler:    _GatewayAPI_PublishMessage_Handler,
		},
		{
			MethodName: "UpdateJobRetries",
			Handler:    _GatewayAPI_UpdateJobRetries_Handler,
		},
		{
			MethodName: "UpdateJobTimeout",
			Handler:    _GatewayAPI_UpdateJobTimeout_Handler,
		},
		{
			MethodName: "DeleteResource",
			Handler:    _GatewayAPI_DeleteResource_Handler,
		},
		{
			MethodName: "ActivateElement",
			Handler:    _GatewayAPI_ActivateElement_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StreamActivatedJobs",
			Handler:       _GatewayAPI_StreamActivatedJobs_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "api/proto/gateway.proto",
}
